const express = require("express");
const userController = require("../controllers/user_controller");
const authController = require("../controllers/auth_controller");
const router = express.Router();
const notifyRouters = require("./notify_routers");
const fileUploader = require("../configs/cloudinary.config");
// router.route("/signup").post(authController.signUp);
// router.route("/login").post(authController.login);
// router.route("/forgotPassword").post(authController.forgotPassword);
// router.route("/resetPassword/:token").get(authController.checkTokenResetPassword).post(authController.resetPassword);
// router.route("/updatePassword").post(authController.protect, authController.updatePassword);
// router.route("/").get(authController.protect, authController.reStrictTo("admin", "user"), userController.getAllUsers);
// router.route("/:id").get(authController.protect, userController.getUser);
// router.route("/upload-avatar").post(authController.protect, fileUploader.single("file"), userController.uploadAvatar);
// router.route("/update").post(authController.protect, userController.updateUser);
router.use("/notifies", notifyRouters);
router.route("/admin").get(authController.protect, authController.reStrictTo("admin"), userController.getAllUsers);
router.route("/admin").post(authController.protect, authController.reStrictTo("admin"), userController.updateUserAdmin);
router.route("/").post(authController.protect, userController.getDetailUser);
router.route("/:account").get(authController.protect, userController.getDetailUserByAccount);
router.route("/update").post(authController.protect, userController.updateDetailUser);
router.route("/follows").post(authController.protect, userController.followsUser);
router.route("/delete-follows").post(authController.protect, userController.deleteFollowsUser);
router.route("/get-all-posts/:userID").get(authController.protect, userController.getAllPostsByAccount);
router.route("/get-all-followings/:userID").get(authController.protect, userController.getAllFollowingsByAccount);
router.route("/get-all-followers/:userID").get(authController.protect, userController.getAllFollowersByAccount);
router.route("/get-posts-count/:userID").get(authController.protect, userController.getPostsCount);
router.route("/reset-password/:token").get(userController.checkTokenResetPassword);
router.route("/reset-password/:token").post(userController.resetPassword);
router.route("/missing-password").post(userController.missingPassword);
router.route("/suggestion-friends/:userID").get(authController.protect, userController.suggestionFriends);
router.route("/active-email/:token").get(userController.checkActiveEmail);
router.route("/active-email").post(authController.protect, userController.activeEmail);
router.route("/check-user").post(userController.checkUser);
router.route("/check-in-room").post(authController.protect, userController.checkUserInRoom);
router.route("/check-user-pending-in-room").post(authController.protect, userController.checkUserPendingInRoom);
router.route("/check-partner-pending-in-room").post(authController.protect, userController.checkPartnerPendingInRoom);
router.route("/restore-user-pending-in-room").get(authController.protect, userController.restoreUserPendingInRoom);
router.route("/sign-up").post(userController.createUser);
router.route("/login").post(userController.loginUser);
router.route("/refresh-token").post(userController.refreshToken);
router.route("/update-all").get(userController.updateAll);
router.route("/create-avatar").get(userController.createAvatar);

module.exports = router;
